### ISSUE TITLE
Ajouter des paramètres au main

### ISSUE THREAD

**Issue by Vayel** [PiggyGenius/GeographicInformationSystem#6]
Pour sélectionner les éléments à afficher.

**Comment by Vayel** [comment]
@Mean-Street peux-tu ajouter un paramètre pour la 14c ? Les instructions à exécuter sont : 

```java
Map<Polygon, Long> grid = DataBase.getDensities(2, 2);
drawer.drawDensities(grid);
```

**Comment by Mean-Street** [comment]
Ok

**Comment by Mean-Street** [comment]
Done. Par contre j'ai pas tes fonctions donc ça peut pas compiler. Tu push ça quand ?

**Comment by Vayel** [comment]
Je viens de push. Mais du coup je l'ai fait aussi, parce qu'il fallait gérer le faire qu'on ne peut pas afficher les densités avec le reste.

**Comment by Mean-Street** [comment]
Pourquoi on peut pas afficher les densités avec le reste ?

**Comment by Vayel** [comment]
Je me suis planté. Je suis en train de gérer la superposition mais ça marche pas.
