### ISSUE TITLE
C'est qui le pédé qui code avec des tabs ?

### ISSUE THREAD

**Issue by Vayel** [PiggyGenius/GeographicInformationSystem#8]
@PiggyGenius

**Comment by Mean-Street** [comment]
# Tabs
- allow mistakes to be more noticeable, it's annoying to micro manage to spaces. 
- are consistent, they are only used for indentation, unless you are commenting wrong. 
- are customizable, you can specify in the options of the editor how wide they are. 
- are more productive, why type 4 spaces when you can hit 1 tab. 
- take less size than multiple spaces. 
- take less time to go through.

Je pose ça là, ne me remercie pas.

**Comment by Vayel** [comment]
> allow mistakes to be more noticeable, it's annoying to micro manage to spaces.

J'ai pas compris.

> are consistent, they are only used for indentation, unless you are commenting wrong.

Et ?

> are customizable, you can specify in the options of the editor how wide they are.

Comment tu gères ce cas ?

```
def x(long_param0, long_param1, long_param2, long_param3,
         long_param4, long_param5):
```

> are more productive, why type 4 spaces when you can hit 1 tab.

Tu as aussi le droit de configurer ton vim pour que tab = 4 spaces.

> take less size than multiple spaces.

Ok.

> take less time to go through.

J'ai pas compris.
